meta:
  version: 2
  flow: FABulousTile
  substituting_steps:
    # IHP uses cumulative antenna rules
    # which aren't supported in repair yet
    OpenROAD.RepairAntennas: null
    # KLayout runs density check, TODO disable
    KLayout.DRC: null

FABULOUS_TILE_DIR: dir::. #tiles/LUT4AB

SYNTH_STRATEGY: "AREA 2" # "AREA 0" "AREA 1" "AREA 2" "AREA 3"

# Basics
DESIGN_NAME: LUT4AB
VERILOG_FILES:
  - dir::../../models_pack.v
  - dir::../../custom.v

# Clock
CLOCK_PERIOD: 20
CLOCK_PORT: UserCLK

# Area
FP_SIZING: absolute
pdk::sky130A:
    DIE_AREA: [0, 0, 205, 225]
    PL_TARGET_DENSITY_PCT: 58
pdk::ihp-sg13g2:
    # Height should be multiple of 0.42 (Metal2 pitch)
    # Width should be multiple of 0.48 (Metal3 pitch)
    #DIE_AREA: [0, 0, 270.24, 236.88]
    #DIE_AREA: [0, 0, 230.4, 250.32]
    
    #DIE_AREA: [0, 0, 239.04, 234.78]
    
    DIE_AREA: [0, 0, 231.84, 241.92]
    
    PL_TARGET_DENSITY_PCT: 80 #68
