meta:
  version: 2
  flow: FABulousTile
  substituting_steps:
    KLayout.DRC: null
    Magic.DRC: null

FABULOUS_TILE_DIR: dir::. #tiles/E_IO

# Basics
DESIGN_NAME: E_IO
VERILOG_FILES:
  - dir::../../models_pack.v
  - dir::../../custom.v
FABULOUS_EXTERNAL_SIDE: E

# Clock
CLOCK_PERIOD: 20
CLOCK_PORT: UserCLK

# Area
FP_SIZING: absolute
pdk::sky130A:
    DIE_AREA: [0, 0, 56.25, 225]
pdk::ihp-sg13g2:
    #DIE_AREA: [0, 0, 63.75, 255]
    DIE_AREA: [0, 0, 59.2, 236.8]
