meta:
  version: 2
  flow: FABulousTile
  substituting_steps:
    # IHP uses cumulative antenna rules
    # which aren't supported in repair yet
    OpenROAD.RepairAntennas: null
    # KLayout runs density check, TODO disable
    KLayout.DRC: null

FABULOUS_TILE_DIR: dir::. #tiles/IHP_SRAM

# Basics
DESIGN_NAME: IHP_SRAM
FABULOUS_SUPERTILE: true
VERILOG_FILES:
  - dir::../../models_pack.v
  - dir::../../custom.v
FABULOUS_EXTERNAL_SIDE: E

# Clock
CLOCK_PERIOD: 20
CLOCK_PORT: Tile_X0Y1_UserCLK

# Area
FP_SIZING: absolute
#DIE_AREA: [0, 0, 100.08, 500.64]
DIE_AREA: [0, 0, 108, 483.84]
#PL_TARGET_DENSITY_PCT: 50
