meta:
  version: 2
  flow: FABulousTile
  substituting_steps:
    # KLayout runs density check, TODO disable
    KLayout.DRC: null

FABULOUS_TILE_DIR: dir::. #tiles/N_term_IHP_SRAM

# Basics
DESIGN_NAME: N_term_IHP_SRAM
VERILOG_FILES:
  - dir::../../models_pack.v
  - dir::../../custom.v

# Clock
CLOCK_PERIOD: 20
CLOCK_PORT: UserCLK

# Area
FP_SIZING: absolute
pdk::ihp-sg13g2:
    #DIE_AREA: [0, 0, 100.08, 60.9]
    
    DIE_AREA: [0, 0, 108, 60.9]
